site_name: Circuit Hacking Mondays
nav:
  - About: index.md
  - Basketball Arduino: basketball-arduino.md
  - Ping Pong Launcher Arduino: pingponglauncher.md
  - Stations: 
      - Station Overview: stations/index.md
      - Basketball Game: stations/basketball.md
      - Led Matrix: stations/ledmatrix.md
      - LCD Screen: stations/lcdscreen.md
      - Motion Alarm: stations/motionalarm.md
      - RGB LED: stations/rgbled.md
theme:
  name: readthedocs
extra_css:
  - css/style.css